// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shaheen.Models;

namespace Shaheen.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    partial class TradeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shaheen.Models.Trade", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("ManufactureCompany")
                        .HasMaxLength(250);

                    b.Property<string>("SupplierCommercialRegistry")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("TestCertificateIssuer")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("TestCertificateNumber")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("TestReportNumber")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Trade");
                });

            modelBuilder.Entity("Shaheen.Models.TradeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("TradeId");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeDetails");
                });

            modelBuilder.Entity("Shaheen.Models.TradeDetail", b =>
                {
                    b.HasOne("Shaheen.Models.Trade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId");
                });
#pragma warning restore 612, 618
        }
    }
}
